/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as CandidateIndexRouteImport } from './routes/candidate/index'
import { Route as JobsNewRouteImport } from './routes/jobs/new'
import { Route as JobsIdRouteImport } from './routes/jobs/$id'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardJobsRouteImport } from './routes/dashboard/jobs'
import { Route as DashboardCandidatesRouteImport } from './routes/dashboard/candidates'
import { Route as JobsIdSessionRouteImport } from './routes/jobs/$id.session'
import { Route as InterviewJoinTokenRouteImport } from './routes/interview/join.$token'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const CandidateIndexRoute = CandidateIndexRouteImport.update({
  id: '/candidate/',
  path: '/candidate/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsNewRoute = JobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIdRoute = JobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardJobsRoute = DashboardJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCandidatesRoute = DashboardCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const JobsIdSessionRoute = JobsIdSessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => JobsIdRoute,
} as any)
const InterviewJoinTokenRoute = InterviewJoinTokenRouteImport.update({
  id: '/interview/join/$token',
  path: '/interview/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/dashboard/candidates': typeof DashboardCandidatesRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/jobs/$id': typeof JobsIdRouteWithChildren
  '/jobs/new': typeof JobsNewRoute
  '/candidate/': typeof CandidateIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/interview/join/$token': typeof InterviewJoinTokenRoute
  '/jobs/$id/session': typeof JobsIdSessionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/dashboard/candidates': typeof DashboardCandidatesRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/jobs/$id': typeof JobsIdRouteWithChildren
  '/jobs/new': typeof JobsNewRoute
  '/candidate': typeof CandidateIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/interview/join/$token': typeof InterviewJoinTokenRoute
  '/jobs/$id/session': typeof JobsIdSessionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/dashboard/candidates': typeof DashboardCandidatesRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/jobs/$id': typeof JobsIdRouteWithChildren
  '/jobs/new': typeof JobsNewRoute
  '/candidate/': typeof CandidateIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/interview/join/$token': typeof InterviewJoinTokenRoute
  '/jobs/$id/session': typeof JobsIdSessionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/about'
    | '/onboarding'
    | '/sign-in'
    | '/dashboard/candidates'
    | '/dashboard/jobs'
    | '/dashboard/settings'
    | '/jobs/$id'
    | '/jobs/new'
    | '/candidate/'
    | '/dashboard/'
    | '/jobs/'
    | '/interview/join/$token'
    | '/jobs/$id/session'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/onboarding'
    | '/sign-in'
    | '/dashboard/candidates'
    | '/dashboard/jobs'
    | '/dashboard/settings'
    | '/jobs/$id'
    | '/jobs/new'
    | '/candidate'
    | '/dashboard'
    | '/jobs'
    | '/interview/join/$token'
    | '/jobs/$id/session'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/about'
    | '/onboarding'
    | '/sign-in'
    | '/dashboard/candidates'
    | '/dashboard/jobs'
    | '/dashboard/settings'
    | '/jobs/$id'
    | '/jobs/new'
    | '/candidate/'
    | '/dashboard/'
    | '/jobs/'
    | '/interview/join/$token'
    | '/jobs/$id/session'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  OnboardingRoute: typeof OnboardingRoute
  SignInRoute: typeof SignInRoute
  JobsIdRoute: typeof JobsIdRouteWithChildren
  JobsNewRoute: typeof JobsNewRoute
  CandidateIndexRoute: typeof CandidateIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
  InterviewJoinTokenRoute: typeof InterviewJoinTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/candidate/': {
      id: '/candidate/'
      path: '/candidate'
      fullPath: '/candidate/'
      preLoaderRoute: typeof CandidateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/new': {
      id: '/jobs/new'
      path: '/jobs/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof JobsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$id': {
      id: '/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof JobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/jobs': {
      id: '/dashboard/jobs'
      path: '/jobs'
      fullPath: '/dashboard/jobs'
      preLoaderRoute: typeof DashboardJobsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/candidates': {
      id: '/dashboard/candidates'
      path: '/candidates'
      fullPath: '/dashboard/candidates'
      preLoaderRoute: typeof DashboardCandidatesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/jobs/$id/session': {
      id: '/jobs/$id/session'
      path: '/session'
      fullPath: '/jobs/$id/session'
      preLoaderRoute: typeof JobsIdSessionRouteImport
      parentRoute: typeof JobsIdRoute
    }
    '/interview/join/$token': {
      id: '/interview/join/$token'
      path: '/interview/join/$token'
      fullPath: '/interview/join/$token'
      preLoaderRoute: typeof InterviewJoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardCandidatesRoute: typeof DashboardCandidatesRoute
  DashboardJobsRoute: typeof DashboardJobsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardCandidatesRoute: DashboardCandidatesRoute,
  DashboardJobsRoute: DashboardJobsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface JobsIdRouteChildren {
  JobsIdSessionRoute: typeof JobsIdSessionRoute
}

const JobsIdRouteChildren: JobsIdRouteChildren = {
  JobsIdSessionRoute: JobsIdSessionRoute,
}

const JobsIdRouteWithChildren =
  JobsIdRoute._addFileChildren(JobsIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  OnboardingRoute: OnboardingRoute,
  SignInRoute: SignInRoute,
  JobsIdRoute: JobsIdRouteWithChildren,
  JobsNewRoute: JobsNewRoute,
  CandidateIndexRoute: CandidateIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
  InterviewJoinTokenRoute: InterviewJoinTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
