/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InterviewsIndexRouteImport } from './routes/interviews/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as CandidateIndexRouteImport } from './routes/candidate/index'
import { Route as InterviewsNewRouteImport } from './routes/interviews/new'
import { Route as InterviewsIdRouteImport } from './routes/interviews/$id'
import { Route as InterviewsIdSessionRouteImport } from './routes/interviews/$id.session'
import { Route as InterviewJoinTokenRouteImport } from './routes/interview/join.$token'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewsIndexRoute = InterviewsIndexRouteImport.update({
  id: '/interviews/',
  path: '/interviews/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateIndexRoute = CandidateIndexRouteImport.update({
  id: '/candidate/',
  path: '/candidate/',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewsNewRoute = InterviewsNewRouteImport.update({
  id: '/interviews/new',
  path: '/interviews/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewsIdRoute = InterviewsIdRouteImport.update({
  id: '/interviews/$id',
  path: '/interviews/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewsIdSessionRoute = InterviewsIdSessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => InterviewsIdRoute,
} as any)
const InterviewJoinTokenRoute = InterviewJoinTokenRouteImport.update({
  id: '/interview/join/$token',
  path: '/interview/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/interviews/$id': typeof InterviewsIdRouteWithChildren
  '/interviews/new': typeof InterviewsNewRoute
  '/candidate/': typeof CandidateIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/interviews/': typeof InterviewsIndexRoute
  '/interview/join/$token': typeof InterviewJoinTokenRoute
  '/interviews/$id/session': typeof InterviewsIdSessionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/interviews/$id': typeof InterviewsIdRouteWithChildren
  '/interviews/new': typeof InterviewsNewRoute
  '/candidate': typeof CandidateIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/interviews': typeof InterviewsIndexRoute
  '/interview/join/$token': typeof InterviewJoinTokenRoute
  '/interviews/$id/session': typeof InterviewsIdSessionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/interviews/$id': typeof InterviewsIdRouteWithChildren
  '/interviews/new': typeof InterviewsNewRoute
  '/candidate/': typeof CandidateIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/interviews/': typeof InterviewsIndexRoute
  '/interview/join/$token': typeof InterviewJoinTokenRoute
  '/interviews/$id/session': typeof InterviewsIdSessionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/onboarding'
    | '/sign-in'
    | '/interviews/$id'
    | '/interviews/new'
    | '/candidate/'
    | '/dashboard/'
    | '/interviews/'
    | '/interview/join/$token'
    | '/interviews/$id/session'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/onboarding'
    | '/sign-in'
    | '/interviews/$id'
    | '/interviews/new'
    | '/candidate'
    | '/dashboard'
    | '/interviews'
    | '/interview/join/$token'
    | '/interviews/$id/session'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/onboarding'
    | '/sign-in'
    | '/interviews/$id'
    | '/interviews/new'
    | '/candidate/'
    | '/dashboard/'
    | '/interviews/'
    | '/interview/join/$token'
    | '/interviews/$id/session'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  OnboardingRoute: typeof OnboardingRoute
  SignInRoute: typeof SignInRoute
  InterviewsIdRoute: typeof InterviewsIdRouteWithChildren
  InterviewsNewRoute: typeof InterviewsNewRoute
  CandidateIndexRoute: typeof CandidateIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  InterviewsIndexRoute: typeof InterviewsIndexRoute
  InterviewJoinTokenRoute: typeof InterviewJoinTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interviews/': {
      id: '/interviews/'
      path: '/interviews'
      fullPath: '/interviews/'
      preLoaderRoute: typeof InterviewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/': {
      id: '/candidate/'
      path: '/candidate'
      fullPath: '/candidate/'
      preLoaderRoute: typeof CandidateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interviews/new': {
      id: '/interviews/new'
      path: '/interviews/new'
      fullPath: '/interviews/new'
      preLoaderRoute: typeof InterviewsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interviews/$id': {
      id: '/interviews/$id'
      path: '/interviews/$id'
      fullPath: '/interviews/$id'
      preLoaderRoute: typeof InterviewsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interviews/$id/session': {
      id: '/interviews/$id/session'
      path: '/session'
      fullPath: '/interviews/$id/session'
      preLoaderRoute: typeof InterviewsIdSessionRouteImport
      parentRoute: typeof InterviewsIdRoute
    }
    '/interview/join/$token': {
      id: '/interview/join/$token'
      path: '/interview/join/$token'
      fullPath: '/interview/join/$token'
      preLoaderRoute: typeof InterviewJoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface InterviewsIdRouteChildren {
  InterviewsIdSessionRoute: typeof InterviewsIdSessionRoute
}

const InterviewsIdRouteChildren: InterviewsIdRouteChildren = {
  InterviewsIdSessionRoute: InterviewsIdSessionRoute,
}

const InterviewsIdRouteWithChildren = InterviewsIdRoute._addFileChildren(
  InterviewsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  OnboardingRoute: OnboardingRoute,
  SignInRoute: SignInRoute,
  InterviewsIdRoute: InterviewsIdRouteWithChildren,
  InterviewsNewRoute: InterviewsNewRoute,
  CandidateIndexRoute: CandidateIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  InterviewsIndexRoute: InterviewsIndexRoute,
  InterviewJoinTokenRoute: InterviewJoinTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
